//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountInfo
    {
        public int UserId { get; set; }
        public string BillingName { get; set; }
        public string BillingAddress1 { get; set; }
        public string BillingAddress2 { get; set; }
        public string BillingCity { get; set; }
        public string BillingState { get; set; }
        public string BillingZip { get; set; }
        public string BillingCountry { get; set; }
        public string BillingPhone { get; set; }
        public string BillingEmailAddress { get; set; }
        public Nullable<bool> AmazonAPI { get; set; }
        public Nullable<bool> EBayAPI { get; set; }
        public Nullable<bool> ShopifyAPI { get; set; }
        public Nullable<bool> CustomerAPI { get; set; }
        public Nullable<bool> Disabled { get; set; }
        public string CreditCardToken { get; set; }
        public Nullable<System.DateTime> StartingDate { get; set; }
        public Nullable<System.DateTime> LastPaymentDate { get; set; }
        public Nullable<decimal> LastPaymentAmount { get; set; }
        public Nullable<bool> AccountPaid { get; set; }
        public Nullable<System.DateTime> NextPaymentDue { get; set; }
        public Nullable<decimal> NextPaymentAmount { get; set; }
    }
}
