//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class BC365Tenant
    {
        public string TenantId { get; set; }
        public string Environment { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string APIVersion { get; set; }
    }
}
