//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class NavAPI
    {
        public int UserId { get; set; }
        public string WSUser { get; set; }
        public string WSDomain { get; set; }
        public string WSPassword { get; set; }
        public string WSServer { get; set; }
        public Nullable<int> WSPortNumber { get; set; }
        public string WSInstanceName { get; set; }
        public string WSCompanyName { get; set; }
        public string EmailAddressForErrors { get; set; }
        public Nullable<int> ODataWSPortNumber { get; set; }
    }
}
